[all:vars]
ansible_connection=ssh

[atacante]
citadel ansible_host=192.168.122.140 ansible_user=anubis

[objetivo]
karnak ansible_host=10.0.0.61 ansible_user=maat

[laboratorio:children]
atacante
objetivo
